;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ExecTask",DevComment="")
+GameplayTagList=(Tag="ExecTask.MovePallet",DevComment="")
+GameplayTagList=(Tag="ExecTask.ReleasePallet",DevComment="")
+GameplayTagList=(Tag="ExecTask.StartTask",DevComment="")
+GameplayTagList=(Tag="ExecTask.TakePallet",DevComment="")
+GameplayTagList=(Tag="Pallet.Free",DevComment="")
+GameplayTagList=(Tag="Pallet.OnShelf",DevComment="")
+GameplayTagList=(Tag="Pallet.OnTask",DevComment="")
+GameplayTagList=(Tag="Status.Free",DevComment="")
+GameplayTagList=(Tag="Status.OnTask",DevComment="")
+GameplayTagList=(Tag="Status.PalletOn",DevComment="")

